//tealium universal tag - utag.124 ut4.0.202605220024, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.encode=function(a,b){b="";try{b=encodeURIComponent(a)}catch(e){utag.DB(e);}if(b==""){b=escape(a);}return b}
u.ev={"view":1};u.scriptrequested=false;u.rp=function(a,b){if(typeof a!=="undefined"&&a.indexOf("@@")>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return u.encode(b[d]);}else{return"";}});}
return a;};u.map={"_sm_124_1":"attribute.id","sales_chat_data_nosidewall":"attribute.data-nosidewall","sales_chat_data_deferee":"attribute.defer","sales_chat_data_noproactive":"attribute.data-proactive"};u.extend=[function(a,b){try{b['_sm_124_1']="oracle_chat";}catch(e){utag.DB(e);}},function(a,b){try{if((typeof b['location_hostname']!='undefined'&&b['location_hostname'].toString().toLowerCase()=='www.oracle.com'.toLowerCase())||(typeof b['location_hostname']!='undefined'&&b['location_hostname'].toString().toLowerCase()=='www-sites.oracle.com'.toLowerCase())||(typeof b['location_hostname']!='undefined'&&b['location_hostname'].toString().toLowerCase()=='www-stage.oracle.com'.toLowerCase())){try{var salesText="Talk to sales";var closeText="Close";var chatText="Chat now";var callSalesTxt="Call Sales";var contactsGlobalLink="/corporate/contact/global.html";var salesContactNumber="+1.800.633.0738";var numberListText="";if(utag_data!==undefined){salesContactNumber=utag_data['sales_contact_number'];if(location.pathname.startsWith('/hr')){salesContactNumber="0800 223 005";}
var siteIdValue=utag_data['meta.siteid'];contactsGlobalLink="/"+siteIdValue+"/corporate/contact/global.html";if(utag_data['meta.siteid']=='us'){contactsGlobalLink="/corporate/contact/global.html";callSalesTxt="Call US Sales";}}
numberListText="Complete list of <a href="+contactsGlobalLink+">local country numbers";if(utag_data['meta.language']=='fr'){salesText="Contacter l&#039équipe commerciale";callSalesTxt="Appeler l&#039équipe commerciale";chatText="Discuter maintenant";numberListText="Liste complète des <a href="+contactsGlobalLink+">numéros de téléphone par pays";}else if(utag_data['meta.language']=='de'){salesText="Mit dem Vertrieb sprechen";callSalesTxt="Vertrieb anrufen";chatText="Jetzt chatten";numberListText="Vollständige Liste der <a href="+contactsGlobalLink+">lokalen Ländernummern";}else if(utag_data['meta.language']=='it'){salesText="Parla con il nostro team vendite";callSalesTxt="Chiama il team vendite";chatText="Avvia una chat";numberListText="Elenco completo dei <a href="+contactsGlobalLink+">numeri nazionali locali";}else if(utag_data['meta.language']=='nl'){salesText="Met Verkoop spreken";callSalesTxt="Verkoop bellen";chatText="Nu chatten";numberListText="Volledige lijst met <a href="+contactsGlobalLink+">lokale landnummers";}else if(utag_data['meta.language']=='es'){salesText="Ponte en contacto con ventas";callSalesTxt="Llama a ventas";chatText="Chatea ahora";numberListText="Lista completa de <a href="+contactsGlobalLink+">números locales por país";}else if(utag_data['meta.language']=='pt'){salesText="Fale com um especialista de vendas";callSalesTxt="Ligue para um especialista de vendas";chatText="Converse com a gente";numberListText="Lista completa de <a href="+contactsGlobalLink+">números locais dos países";}
var chatHTML="<ocom-chatbot sales-txt='"+salesText+"' chat-txt='"+chatText+"' close-txt='"+closeText+"' number-txt='"+callSalesTxt+"' number='"+salesContactNumber+"' number-list='"+numberListText+"' proactive='5'></ocom-chatbot>"
document.getElementsByTagName("body")[0].insertAdjacentHTML('beforeend',chatHTML);}catch(e){console.log(e);}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&"||"&","kvp_delim":"="||"=","qs_delim":"?"||"?","tag_type":"script","base_url":"/asset/sequoia/js/wc-chatbot.js","secure_base_url":"","static_params":"","cachebust":"disabled","cachevar":""||"_rnd","requestscriptonce":"enabled","attribute":{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:124:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("attribute.")===0){if(e[f].indexOf("attribute.data")===0&&b[d]=="empty-string"){b[d]=b[d].replace("empty-string","");}
u.data.attribute[e[f].split(".")[1]]=b[d];}else if(!u.data.hasOwnProperty(e[f])){c.push(e[f]+"##kvp_delim##"+u.encode(b[d]));}
u.data[e[f]]=b[d];}}}
if(!u.data.base_url){if(!u.data.secure_base_url){utag.DB("Error: No Base URL or Secure HTTPS Override Provided.");return;}else{u.data.base_url=u.data.secure_base_url;utag.DB("No Base URL provided, using Secure HTTPS Override.");}}
u.data.secure_base_url=u.data.secure_base_url||u.data.base_url;u.data.url=(location.protocol==="https:"?u.data.secure_base_url:u.data.base_url);if(u.data.url.indexOf("http")!==0&&u.data.url.indexOf("/")!==0){u.data.url=location.protocol+"//"+u.data.url;}
if(u.data.static_params){c.push(u.data.static_params);}
var cb_check=new RegExp("(\\"+u.data.qs_delim+"|"+u.data.qsp_delim+")"+u.data.cachevar+"=");if(u.data.cachebust==="enabled"&&!cb_check.test(u.data.url)){c.push([u.data.cachevar,Math.random()].join(u.data.kvp_delim));}
if(c.length>0){if(u.data.url.indexOf(u.data.qs_delim)<0){u.data.url+=u.data.qs_delim;}else if(u.data.url.indexOf(u.data.qs_delim)!==(u.data.url.length-1)){u.data.url+=u.data.qsp_delim;}}
u.data.url=u.rp(u.data.url,b)+u.rp(c.join(u.data.qsp_delim),b);u.data.url=u.data.url.replace(/##kvp_delim##/g,u.data.kvp_delim);u.callback=u.callback||function(){};if(u.data.requestscriptonce==="enabled"&&u.data.tag_type==="script"){if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_124","cb":u.callback,"attrs":u.data.attribute});}else{u.callback();}}else{u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_124","cb":u.callback,"attrs":u.data.attribute});}
utag.DB("send:124:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("124","oracle.main"));}catch(error){utag.DB(error);}
